name: cap_reserve
version: 0.1.0
authors:
  - Winton Welsh
email: mail@wintoni.us
homepage: https://github.com/winton/cap_reserve
summary:
description:
dependencies:
  - nestful
development_dependencies:
  - rake
  - rspec